version: "3.8"
services:
  dashboard:
    build:
      dockerfile: ./Docker/app.dockerfile
      context: .
    container_name: mdp-dashboard
    restart: always
    environment:
      VERBOSITY: ${VERBOSITY:-INFO}
    ports:
      - "8501:8501"
    # volumes:
      # persist the data of the dasbhboard
      # - ${DEPLOY_VOLUMES_DIR:-/opt/streamlit}:/streamlit/data

# volumes:
#   dashboard-data: null
