CREATE TABLE [dbo].[WRH_PROVINCE_HEALTH](
    [DATE_LOADING] date,
	[ANNO] int,
	[PROVINCIA] nvarchar(50),
	[GENERE] char(1),
	[SPERANZA_VITA_NASCITA] float,
	[TASSO_MORTALITA] float,
	[TASSO_MORTALITA_INFANTILE] float,
	PRIMARY KEY ([ANNO],[PROVINCIA],[GENERE])
);