CREATE TABLE WRH_ATS_DIAGNOSES
(
ANNO INT,
COD_ATS INT,
COD_ACC_DIAGNOSI INT,
DESCRIZIONE_ACC_DI_DIAGNOSI NVARCHAR(1000),
TASSO_RICOVERI_STESSA_ATS FLOAT,
TASSO_RICOVERI_ALTRA_ATS FLOAT,
PRIMARY KEY(ANNO,COD_ATS,COD_ACC_DIAGNOSI)
);