CREATE TABLE [dbo].[WRH_PERFORMANCE_HOSPITAL](
	[ANNO] [int] NOT NULL,
	[COD_STRUTTURA] [char](9) NOT NULL,
	[NUM_TOTALE_RICOVERI] [int] NULL,
	[NUM_DIMISSIONI_VOLONTARIE] [int] NULL,
	[NUM_TOTALE_DIMISSIONI] [int] NULL,
	[NUM_TRASFERIMENTI_FRA_STRUTTURE] [int] NULL,
	[NUM_RICOVERI_RIPETUTI] [int] NULL,
	[NUM_RITORNI_IN_SALA_OPERATORIA] [int] NULL,
	[NUM_DI_RICOVERI_DI_TIPO_CHIRURGICO] [int] NULL,
	PRIMARY KEY (ANNO,COD_STRUTTURA)
);
